/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */


import { HTMLStencilElement, JSXBase } from '@stencil/core/internal';


export namespace Components {
  interface DkButton {
    /**
    * If `true`, the user cannot interact with the button.
    */
    'disabled': boolean;
    /**
    * If `true` and disabled is `true`, only aria-disable prop will be true.
    */
    'focusable': boolean;
    /**
    * The type of the button.
    */
    'type': 'submit' | 'reset' | 'button';
  }
}

declare global {


  interface HTMLDkButtonElement extends Components.DkButton, HTMLStencilElement {}
  var HTMLDkButtonElement: {
    prototype: HTMLDkButtonElement;
    new (): HTMLDkButtonElement;
  };
  interface HTMLElementTagNameMap {
    'dk-button': HTMLDkButtonElement;
  }
}

declare namespace LocalJSX {
  interface DkButton {
    /**
    * If `true`, the user cannot interact with the button.
    */
    'disabled'?: boolean;
    /**
    * If `true` and disabled is `true`, only aria-disable prop will be true.
    */
    'focusable'?: boolean;
    /**
    * The type of the button.
    */
    'type'?: 'submit' | 'reset' | 'button';
  }

  interface IntrinsicElements {
    'dk-button': DkButton;
  }
}

export { LocalJSX as JSX };


declare module "@stencil/core" {
  export namespace JSX {
    interface IntrinsicElements {
      'dk-button': LocalJSX.DkButton & JSXBase.HTMLAttributes<HTMLDkButtonElement>;
    }
  }
}


