/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */


import { HTMLStencilElement, JSXBase } from '@stencil/core/internal';


export namespace Components {
  interface DkButton {
    /**
    * If `true`, the user cannot interact with the button.
    */
    'disabled': boolean;
    /**
    * The type of the button.
    */
    'type': 'submit' | 'reset' | 'button';
  }
  interface DkCheckbox {
    /**
    * The unique identifier of checkbox
    */
    'id': string;
    /**
    * The label of checkbox
    */
    'label': string;
    /**
    * The unique identifier of checkbox
    */
    'name': string;
  }
}

declare global {


  interface HTMLDkButtonElement extends Components.DkButton, HTMLStencilElement {}
  var HTMLDkButtonElement: {
    prototype: HTMLDkButtonElement;
    new (): HTMLDkButtonElement;
  };

  interface HTMLDkCheckboxElement extends Components.DkCheckbox, HTMLStencilElement {}
  var HTMLDkCheckboxElement: {
    prototype: HTMLDkCheckboxElement;
    new (): HTMLDkCheckboxElement;
  };
  interface HTMLElementTagNameMap {
    'dk-button': HTMLDkButtonElement;
    'dk-checkbox': HTMLDkCheckboxElement;
  }
}

declare namespace LocalJSX {
  interface DkButton {
    /**
    * If `true`, the user cannot interact with the button.
    */
    'disabled'?: boolean;
    'onOnClick'?: (event: CustomEvent<any>) => void;
    /**
    * The type of the button.
    */
    'type'?: 'submit' | 'reset' | 'button';
  }
  interface DkCheckbox {
    /**
    * The unique identifier of checkbox
    */
    'id'?: string;
    /**
    * The label of checkbox
    */
    'label'?: string;
    /**
    * The unique identifier of checkbox
    */
    'name'?: string;
  }

  interface IntrinsicElements {
    'dk-button': DkButton;
    'dk-checkbox': DkCheckbox;
  }
}

export { LocalJSX as JSX };


declare module "@stencil/core" {
  export namespace JSX {
    interface IntrinsicElements {
      'dk-button': LocalJSX.DkButton & JSXBase.HTMLAttributes<HTMLDkButtonElement>;
      'dk-checkbox': LocalJSX.DkCheckbox & JSXBase.HTMLAttributes<HTMLDkCheckboxElement>;
    }
  }
}


